### ISSUE TITLE
Flashlights

### ISSUE THREAD

**Issue by chrisly67** [Speedy1985/enigmalight#7]
Hi Speedy.
Yesterday I´ve changed from Boblight to Enigmalight - updating was very easy (thanks for the ConfigEditor!).
But I have big problems with flashlights:
Boblight = 2 - 5 flashlights / hour
Enigmalight = 2 - 10 flashlights / minute

It will be better, when interval is > 0,3 (but then it´s not fast enough and there are still more flashlights than with Boblight).
Any idea?

**Comment by chrisly67** [comment]
Hi Speedy.
Is it possible, that the flashlights are a special problem of sedulight?

**Comment by digiTaler1** [comment]
It's not a problem of sedulight but of the device USB0! ACM0 Hardware works without flash lights.

**Comment by Kalli1972** [comment]
I have the Problem with flickering to. I use a DM7080 and all 10-15 sec. the lights are flashing. I have a Sedu Light V2 in use. My output  /dev/ttyUSB0 
What can i do?

Ich habe das Problem mit dem öfteren Aufflackern ebenfalls. Anggeschlossen an meine DM7080 ist ein Sedu Light V2. Ansonsten läufts nahezu perfekt! Da es aber schon meiner Frau aufgefallen ist, wäre eine Lösung wünschenswert...
Also bitte was kann man tun?

**Comment by Kalli1972** [comment]
Dank derHilfe von digiTaler1 und Cypress konnte ich das Problem für die Kombi Sedu Light V2 und Dm7080 mit folgenden Änderungen lösen:

[global]
interface	127.0.0.1
port		19333

[device]
threadpriority  99
name		ambilight
output		/dev/ttyUSB0
type		momo
interval		20000
prefix		5A B0
postfix		A5
channels	768
rate		500000
debug		off
delayafteropen		1000000

Offensichtlich muss immer das Große Prefix eingestellt werden.
Jetzt läuft es perfekt!!!
Nochmals Danke!!!

**Comment by chrisly67** [comment]
Klappt wunderbar. Danke!!!
Config with Sedu 768 works fine!
